Allow merge

diff --git a/.github/workflows/app-common-bundle-publish.yml b/.github/workflows/app-common-bundle-publish.yml
--- a/.github/workflows/app-common-bundle-publish.yml
+++ b/.github/workflows/app-common-bundle-publish.yml
@@ -57,6 +57,8 @@ permissions:
   contents: read
 
 jobs:
+  license_check:
+    uses: ./.github/workflows/license-check-ci.yml
 
   build_and_publish:
 
@@ -143,3 +145,25 @@ jobs:
           CONTENT_CHANGED: ${{ steps.changed-content.outputs.any_changed }}
           NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
           NUPKG_RECURSE_PATH: 'source/App/source'
+
+  #
+  # Branch policy status check
+  #
+
+  allow_merge:
+    runs-on: ubuntu-latest
+    needs: [
+      license_check,
+      build_and_publish
+    ]
+    if: |
+      always()
+    steps:
+      - name: Verify if merge is allowed
+        run: |
+          echo "${{ toJSON(needs) }}"
+
+          if [[ ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }} = true ]]; then
+              echo "Failed"
+              exit 1
+          fi
